### ISSUE TITLE
Fix cleanup of ghost screens upon failure

### ISSUE THREAD

**Issue by onemustpersist** [usetrmnl/byos_hanami#208]
I have to assume they are failed ones as there are more then screens created. In web/uploads, more files exist then screens created.

I assume this is related to the 422 issue before of submitting a screen that exists and on failure the upload that has already been saved to disk, is not being cleaned up on error.

**Comment by bkuhlmann** [comment]
This was fixed in yesterday's build where, yes, some screen would not be properly cleaned up. Please grab the latest build to correct. You might need delete your existing screens and then zero out the uploads folder to clean up first, though.

**Comment by onemustpersist** [comment]
This is still happening when using PATCH.

Create a screen on new system, clear uploads folder.

Add screen via post

Note single file in uploads folder.

PATCH content X amount of times.

Note upload files are 1+X

**Comment by bkuhlmann** [comment]
Sorry, fixed with a temporary patch. Also fixed in Version 0.21.0. I'm working to consolidate the logic so this attachments can be simply upserted to prevent this from happening further.

**Comment by onemustpersist** [comment]
I think that patch may have been a bit aggressive on deletions:

<img width="1975" height="333" alt="Image" src="https://github.com/user-attachments/assets/0c0f6163-a63f-4647-8106-2508ab430c46" />

**Comment by bkuhlmann** [comment]
To confirm, you are using the latest build? What this looks like to me is that the attached images to your screens are missing entirely and could be from manually deleting the associated file in the `public/uploads` folder? If so, that would explain why your screens have nothing to render because the files are missing.

**Comment by onemustpersist** [comment]
Yes, I am on the latest. I am pushing new content constantly via PATCH endpoint, so regardless of if the folder was cleared or not there should be images there now by now.

**Comment by bkuhlmann** [comment]
Hmm, the only way I can recreate that is by deleting the associated attachments. Are you seeing errors in your logs? Also, if you delete those screens and then create/patch them, does the problem persist?

**Comment by bkuhlmann** [comment]
OK, that's the issue then because HTTP PATCH *does not create a new resource*, only partially updates *an existing resource*. Use POST to create, and PATCH to partially update and you'll be good-to-go.

**Comment by onemustpersist** [comment]
Ok, it is not just the patch. I deleted all screens via ui. Let my tool create the screens again (same names) and keep updating it. 

Looking at the logs, it is still cleaning up if it error while generating:
```
"message":"Browser did not produce websocket url within 10 seconds, try to increase `:process_timeout`. See https://github.com/rubycdp/ferrum#customization","backtrace":["/usr/local/bundle/ruby/3.4.0/gems/ferrum-0.17.1/lib/ferrum/browser/process.rb:170:in 'Ferrum::Browser::Process#parse_ws_url'","/usr/local/bundle/ruby/3.4.0/gems/ferrum-0.17.1/lib/ferrum/browser/process.rb:104:in 'Ferrum::Browser::Process#start'","/usr/local/bundle/ruby/3.4.0/gems/ferrum-0.17.1/lib/ferrum/browser.rb:277:in 'Ferrum::Browser#start'","/usr/local/bundle/ruby/3.4.0/gems/ferrum-0.17.1/lib/ferrum/browser.rb:136:in 'Ferrum::Browser#initialize'","/app/app/aspects/screens/shoter.rb:44:in 'Class#new'","/app/app/aspects/screens/shoter.rb:44:in 'block in Terminus::Aspects::Screens::Shoter#save'","/usr/local/lib/ruby/3.4.0/pathname.rb:615:in 'block in Pathname.mktmpdir'","/usr/local/lib/ruby/3.4.0/tmpdir.rb:105:in 'Dir.mktmpdir'","/usr/local/lib/ruby/3.4.0/pathname.rb:613:in 'Pathname.mktmpdir'","/app/app/aspects/screens/shoter.rb:43:in 'Terminus::Aspects::Screens::Shoter#save'","/app/app/aspects/screens/shoter.rb:34:in 'Terminus::Aspects::Screens::Shoter#call'","/app/app/aspects/screens/creators/temp_path.rb:23:in 'block in Terminus::Aspects::Screens::Creators::TempPath#process'","<internal:kernel>:126:in 'Kernel#then'","/app/app/aspects/screens/creators/temp_path.rb:23:in 'Terminus::Aspects::Screens::Creators::TempPath#process'","/app/app/aspects/screens/creators/temp_path.rb:17:in 'block in Terminus::Aspects::Screens::Creators::TempPath#call'","/usr/local/lib/ruby/3.4.0/pathname.rb:615:in 'block in Pathname.mktmpdir'","/usr/local/lib/ruby/3.4.0/tmpdir.rb:105:in 'Dir.mktmpdir'","/usr/local/lib/ruby/3.4.0/pathname.rb:613:in 'Pathname.mktmpdir'","/app/app/aspects/screens/creators/temp_path.rb:17:in 'Terminus::Aspects::Screens::Creators::TempPath#call'","/app/app/actions/api/screens/patch.rb:57:in 'Terminus::Actions::API::Screens::Patch#update'","/app/app/actions/api/screens/patch.rb:41:in 'Terminus::Actions::API::Screens::Patch#handle'","/usr/local/bundle/ruby/3.4.0/gems/hanami-controller-2.2.0/lib/hanami/action.rb:329:in 'block in Hanami::Action#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-controller-2.2.0/lib/hanami/action.rb:310:in 'Kernel#catch'","/usr/local/bundle/ruby/3.4.0/gems/hanami-controller-2.2.0/lib/hanami/action.rb:310:in 'Hanami::Action#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-2.2.1/lib/hanami/slice/routing/resolver.rb:78:in 'block in Hanami::Slice::Routing::Resolver#resolve_slice_action'","/usr/local/bundle/ruby/3.4.0/gems/hanami-router-2.2.0/lib/hanami/router.rb:109:in 'Hanami::Router#call'","/app/app/aspects/screens/designer/middleware.rb:31:in 'Terminus::Aspects::Screens::Designer::Middleware#call'","/usr/local/bundle/ruby/3.4.0/gems/rack-2.2.17/lib/rack/static.rb:162:in 'Rack::Static#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-router-2.2.0/lib/hanami/middleware/body_parser.rb:52:in 'Hanami::Middleware::BodyParser#call'","/usr/local/bundle/ruby/3.4.0/gems/rack-2.2.17/lib/rack/deflater.rb:44:in 'Rack::Deflater#call'","/usr/local/bundle/ruby/3.4.0/gems/rack-attack-6.7.0/lib/rack/attack.rb:110:in 'Rack::Attack#call'","/usr/local/bundle/ruby/3.4.0/gems/rack-2.2.17/lib/rack/static.rb:162:in 'Rack::Static#call'","/usr/local/bundle/ruby/3.4.0/gems/rack-2.2.17/lib/rack/method_override.rb:24:in 'Rack::MethodOverride#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-2.2.1/lib/hanami/middleware/render_errors.rb:57:in 'Hanami::Middleware::RenderErrors#call'","/usr/local/bundle/ruby/3.4.0/gems/dry-monitor-1.0.1/lib/dry/monitor/rack/middleware.rb:36:in 'block in Dry::Monitor::Rack::Middleware#call'","/usr/local/bundle/ruby/3.4.0/gems/dry-monitor-1.0.1/lib/dry/monitor/clock.rb:15:in 'Dry::Monitor::Clock#measure'","/usr/local/bundle/ruby/3.4.0/gems/dry-monitor-1.0.1/lib/dry/monitor/rack/middleware.rb:36:in 'Dry::Monitor::Rack::Middleware#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-router-2.2.0/lib/hanami/middleware/app.rb:40:in 'Hanami::Middleware::App#call'","/usr/local/bundle/ruby/3.4.0/gems/hanami-2.2.1/lib/hanami/slice.rb:791:in 'Hanami::Slice::ClassMethods#call'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/configuration.rb:279:in 'Puma::Configuration::ConfigMiddleware#call'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/request.rb:99:in 'block in Puma::Request#handle_request'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/thread_pool.rb:390:in 'Puma::ThreadPool#with_force_shutdown'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/request.rb:98:in 'Puma::Request#handle_request'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/server.rb:472:in 'Puma::Server#process_client'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/server.rb:254:in 'block in Puma::Server#run'","/usr/local/bundle/ruby/3.4.0/gems/puma-6.6.1/lib/puma/thread_pool.rb:167:in 'block in Puma::ThreadPool#spawn_thread'"]}
```

Looks to related to chrome generating the images failing, then deleting the images that were there? However, in this scenario, it *DOES* update with a patch?

**Comment by bkuhlmann** [comment]
Thanks. Yeah, this seems to stem from Chrome not being able to create an image in time which is new. Haven't seen that before so will need to figure out a way to reproduce.
